name: Dependency-Check and SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Устанавливаем OWASP Dependency-Check через CLI
      - name: Download and run OWASP Dependency-Check
        run: |
          # Скачиваем и распаковываем Dependency-Check
          curl -sLO https://github.com/jeremylong/DependencyCheck/releases/download/v9.0.10/dependency-check-9.0.10-release.zip
          unzip dependency-check-9.0.10-release.zip
          chmod +x ./dependency-check/bin/dependency-check.sh
          
          # Запускаем сканирование
          ./dependency-check/bin/dependency-check.sh \
            --project "Your Project Name" \
            --scan "." \
            --format "HTML" \
            --out "./dependency-check-report"
        
      - name: Upload Dependency-Check report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report/

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          token: ${{ secrets.SONAR_TOKEN }}
          projectKey: your-project-key
          organization: your-organization