name: Dependency-Check and SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run OWASP Dependency-Check
        uses: dependency-check/owasp-dependency-check-action@v2
        with:
          scan: './'
          format: 'HTML'
          outputDirectory: './dependency-check-report'

      - name: Upload Dependency-Check report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: dependency-check-report/

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          # ВАЖНО: замените на ваш SonarQube/SonarCloud токен в секретах репозитория
          token: ${{ secrets.SONAR_TOKEN }}
          # Ключ проекта SonarQube (замените на свой)
          projectKey: your-project-key
          # Название организации (если используете SonarCloud)
          organization: your-organization
          # Дополнительные параметры (если нужны)
          # sonar.sources: '.'
